version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    stdin_open: true
    command: ["npm", "start"]

volumes:
  postgres_data: